name: build

on: [push, pull_request]

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        git clone https://github.com/libusb/libusb -b v1.0.29
        pushd libusb
        ./autogen.sh --prefix=/usr --enable-shared=no --enable-udev=no
        make
        sudo make install
        popd
        rm -rf libusb
        cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXE_LINKER_FLAGS="-static-libgcc -static-libstdc++ -static" -DDISABLE_FRONTEND=ON
        cmake --build build
    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-build
        path: build/bin/*

  macos-arm64-build:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        sed -i .bak 's/-framework CoreFoundation/-framework CoreFoundation -framework Security/g' heimdall/CMakeLists.txt
        cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DDISABLE_FRONTEND=ON
        cmake --build build
    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-arm64-build
        path: build/bin/heimdall

  macos-x86_64-build:
    runs-on: macos-15-intel

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        sed -i .bak 's/-framework CoreFoundation/-framework CoreFoundation -framework Security/g' heimdall/CMakeLists.txt
        rm /usr/local/Cellar/libusb/*/lib/libusb-1.0.0.dylib
        cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DDISABLE_FRONTEND=ON
        cmake --build build
    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-x86_64-build
        path: build/bin/heimdall

  macos-build:
    runs-on: macos-15
    needs: [macos-x86_64-build, macos-arm64-build]

    steps:
    - name: Download arm64 build
      uses: actions/download-artifact@v4
      with:
        name: macos-arm64-build
        path: src/arm64
    - name: Download x86_64 build
      uses: actions/download-artifact@v4
      with:
        name: macos-x86_64-build
        path: src/x86_64
    - name: Delete macOS builds
      uses: geekyeggo/delete-artifact@v6
      with:
        name: |
          macos-arm64-build
          macos-x86_64-build
    - name: Build
      run: |
        lipo -create -output src/heimdall src/x86_64/heimdall src/arm64/heimdall
        rm -rf src/arm64 src/x86_64
        chmod +x src/heimdall
        ln -sf /usr/local/bin src/:usr:local:bin:
        hdiutil create -volname Heimdall -srcfolder src -ov -format UDZO Heimdall.dmg
    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: Heimdall.dmg

  win-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-libusb
    - name: Build
      shell: msys2 {0}
      run: |
        cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DDISABLE_FRONTEND=ON
        cmake --build build
        cp /c/a/_temp/msys64/mingw64/bin/libusb-1.0.dll build/bin
    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: win64-build
        path: build/bin/*
